// flow-typed signature: 6c95c05a4e6bbd20167ef2d119f06bba
// flow-typed version: <<STUB>>/popmotion-react_v^2.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'popmotion-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'popmotion-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'popmotion-react/lib/index' {
  declare module.exports: any;
}

declare module 'popmotion-react/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'popmotion-react/lib/index.js' {
  declare module.exports: $Exports<'popmotion-react/lib/index'>;
}
declare module 'popmotion-react/src/index.js' {
  declare module.exports: $Exports<'popmotion-react/src/index'>;
}
