// flow-typed signature: 53ffef6707cc4c595ac27ed0e4d5e1b3
// flow-typed version: <<STUB>>/popmotion_v^8.1.9/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'popmotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'popmotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'popmotion/action/index' {
  declare module.exports: any;
}

declare module 'popmotion/action/types' {
  declare module.exports: any;
}

declare module 'popmotion/action/vector' {
  declare module.exports: any;
}

declare module 'popmotion/animations/decay/index' {
  declare module.exports: any;
}

declare module 'popmotion/animations/decay/types' {
  declare module.exports: any;
}

declare module 'popmotion/animations/every-frame/index' {
  declare module.exports: any;
}

declare module 'popmotion/animations/keyframes/index' {
  declare module.exports: any;
}

declare module 'popmotion/animations/keyframes/types' {
  declare module.exports: any;
}

declare module 'popmotion/animations/physics/index' {
  declare module.exports: any;
}

declare module 'popmotion/animations/physics/types' {
  declare module.exports: any;
}

declare module 'popmotion/animations/spring/index' {
  declare module.exports: any;
}

declare module 'popmotion/animations/spring/types' {
  declare module.exports: any;
}

declare module 'popmotion/animations/timeline/index' {
  declare module.exports: any;
}

declare module 'popmotion/animations/timeline/types' {
  declare module.exports: any;
}

declare module 'popmotion/animations/tween/index' {
  declare module.exports: any;
}

declare module 'popmotion/animations/tween/scrubber' {
  declare module.exports: any;
}

declare module 'popmotion/animations/tween/types' {
  declare module.exports: any;
}

declare module 'popmotion/calc' {
  declare module.exports: any;
}

declare module 'popmotion/chainable/index' {
  declare module.exports: any;
}

declare module 'popmotion/chainable/types' {
  declare module.exports: any;
}

declare module 'popmotion/compositors/chain' {
  declare module.exports: any;
}

declare module 'popmotion/compositors/composite' {
  declare module.exports: any;
}

declare module 'popmotion/compositors/crossfade' {
  declare module.exports: any;
}

declare module 'popmotion/compositors/delay' {
  declare module.exports: any;
}

declare module 'popmotion/compositors/merge' {
  declare module.exports: any;
}

declare module 'popmotion/compositors/multi' {
  declare module.exports: any;
}

declare module 'popmotion/compositors/parallel' {
  declare module.exports: any;
}

declare module 'popmotion/compositors/schedule' {
  declare module.exports: any;
}

declare module 'popmotion/compositors/stagger' {
  declare module.exports: any;
}

declare module 'popmotion/dist/popmotion.global.min' {
  declare module.exports: any;
}

declare module 'popmotion/dist/popmotion.xl.min' {
  declare module.exports: any;
}

declare module 'popmotion/easing' {
  declare module.exports: any;
}

declare module 'popmotion/global-xl' {
  declare module.exports: any;
}

declare module 'popmotion/global' {
  declare module.exports: any;
}

declare module 'popmotion/input/listen/index' {
  declare module.exports: any;
}

declare module 'popmotion/input/listen/types' {
  declare module.exports: any;
}

declare module 'popmotion/input/multitouch/index' {
  declare module.exports: any;
}

declare module 'popmotion/input/pointer/index' {
  declare module.exports: any;
}

declare module 'popmotion/input/pointer/mouse' {
  declare module.exports: any;
}

declare module 'popmotion/input/pointer/types' {
  declare module.exports: any;
}

declare module 'popmotion/input/pointer/utils' {
  declare module.exports: any;
}

declare module 'popmotion/observer/index' {
  declare module.exports: any;
}

declare module 'popmotion/observer/types' {
  declare module.exports: any;
}

declare module 'popmotion/reactions/index' {
  declare module.exports: any;
}

declare module 'popmotion/reactions/multicast' {
  declare module.exports: any;
}

declare module 'popmotion/reactions/types' {
  declare module.exports: any;
}

declare module 'popmotion/reactions/value' {
  declare module.exports: any;
}

declare module 'popmotion/transformers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'popmotion/action/index.js' {
  declare module.exports: $Exports<'popmotion/action/index'>;
}
declare module 'popmotion/action/types.js' {
  declare module.exports: $Exports<'popmotion/action/types'>;
}
declare module 'popmotion/action/vector.js' {
  declare module.exports: $Exports<'popmotion/action/vector'>;
}
declare module 'popmotion/animations/decay/index.js' {
  declare module.exports: $Exports<'popmotion/animations/decay/index'>;
}
declare module 'popmotion/animations/decay/types.js' {
  declare module.exports: $Exports<'popmotion/animations/decay/types'>;
}
declare module 'popmotion/animations/every-frame/index.js' {
  declare module.exports: $Exports<'popmotion/animations/every-frame/index'>;
}
declare module 'popmotion/animations/keyframes/index.js' {
  declare module.exports: $Exports<'popmotion/animations/keyframes/index'>;
}
declare module 'popmotion/animations/keyframes/types.js' {
  declare module.exports: $Exports<'popmotion/animations/keyframes/types'>;
}
declare module 'popmotion/animations/physics/index.js' {
  declare module.exports: $Exports<'popmotion/animations/physics/index'>;
}
declare module 'popmotion/animations/physics/types.js' {
  declare module.exports: $Exports<'popmotion/animations/physics/types'>;
}
declare module 'popmotion/animations/spring/index.js' {
  declare module.exports: $Exports<'popmotion/animations/spring/index'>;
}
declare module 'popmotion/animations/spring/types.js' {
  declare module.exports: $Exports<'popmotion/animations/spring/types'>;
}
declare module 'popmotion/animations/timeline/index.js' {
  declare module.exports: $Exports<'popmotion/animations/timeline/index'>;
}
declare module 'popmotion/animations/timeline/types.js' {
  declare module.exports: $Exports<'popmotion/animations/timeline/types'>;
}
declare module 'popmotion/animations/tween/index.js' {
  declare module.exports: $Exports<'popmotion/animations/tween/index'>;
}
declare module 'popmotion/animations/tween/scrubber.js' {
  declare module.exports: $Exports<'popmotion/animations/tween/scrubber'>;
}
declare module 'popmotion/animations/tween/types.js' {
  declare module.exports: $Exports<'popmotion/animations/tween/types'>;
}
declare module 'popmotion/calc.js' {
  declare module.exports: $Exports<'popmotion/calc'>;
}
declare module 'popmotion/chainable/index.js' {
  declare module.exports: $Exports<'popmotion/chainable/index'>;
}
declare module 'popmotion/chainable/types.js' {
  declare module.exports: $Exports<'popmotion/chainable/types'>;
}
declare module 'popmotion/compositors/chain.js' {
  declare module.exports: $Exports<'popmotion/compositors/chain'>;
}
declare module 'popmotion/compositors/composite.js' {
  declare module.exports: $Exports<'popmotion/compositors/composite'>;
}
declare module 'popmotion/compositors/crossfade.js' {
  declare module.exports: $Exports<'popmotion/compositors/crossfade'>;
}
declare module 'popmotion/compositors/delay.js' {
  declare module.exports: $Exports<'popmotion/compositors/delay'>;
}
declare module 'popmotion/compositors/merge.js' {
  declare module.exports: $Exports<'popmotion/compositors/merge'>;
}
declare module 'popmotion/compositors/multi.js' {
  declare module.exports: $Exports<'popmotion/compositors/multi'>;
}
declare module 'popmotion/compositors/parallel.js' {
  declare module.exports: $Exports<'popmotion/compositors/parallel'>;
}
declare module 'popmotion/compositors/schedule.js' {
  declare module.exports: $Exports<'popmotion/compositors/schedule'>;
}
declare module 'popmotion/compositors/stagger.js' {
  declare module.exports: $Exports<'popmotion/compositors/stagger'>;
}
declare module 'popmotion/dist/popmotion.global.min.js' {
  declare module.exports: $Exports<'popmotion/dist/popmotion.global.min'>;
}
declare module 'popmotion/dist/popmotion.xl.min.js' {
  declare module.exports: $Exports<'popmotion/dist/popmotion.xl.min'>;
}
declare module 'popmotion/easing.js' {
  declare module.exports: $Exports<'popmotion/easing'>;
}
declare module 'popmotion/global-xl.js' {
  declare module.exports: $Exports<'popmotion/global-xl'>;
}
declare module 'popmotion/global.js' {
  declare module.exports: $Exports<'popmotion/global'>;
}
declare module 'popmotion/index' {
  declare module.exports: $Exports<'popmotion'>;
}
declare module 'popmotion/index.js' {
  declare module.exports: $Exports<'popmotion'>;
}
declare module 'popmotion/input/listen/index.js' {
  declare module.exports: $Exports<'popmotion/input/listen/index'>;
}
declare module 'popmotion/input/listen/types.js' {
  declare module.exports: $Exports<'popmotion/input/listen/types'>;
}
declare module 'popmotion/input/multitouch/index.js' {
  declare module.exports: $Exports<'popmotion/input/multitouch/index'>;
}
declare module 'popmotion/input/pointer/index.js' {
  declare module.exports: $Exports<'popmotion/input/pointer/index'>;
}
declare module 'popmotion/input/pointer/mouse.js' {
  declare module.exports: $Exports<'popmotion/input/pointer/mouse'>;
}
declare module 'popmotion/input/pointer/types.js' {
  declare module.exports: $Exports<'popmotion/input/pointer/types'>;
}
declare module 'popmotion/input/pointer/utils.js' {
  declare module.exports: $Exports<'popmotion/input/pointer/utils'>;
}
declare module 'popmotion/observer/index.js' {
  declare module.exports: $Exports<'popmotion/observer/index'>;
}
declare module 'popmotion/observer/types.js' {
  declare module.exports: $Exports<'popmotion/observer/types'>;
}
declare module 'popmotion/reactions/index.js' {
  declare module.exports: $Exports<'popmotion/reactions/index'>;
}
declare module 'popmotion/reactions/multicast.js' {
  declare module.exports: $Exports<'popmotion/reactions/multicast'>;
}
declare module 'popmotion/reactions/types.js' {
  declare module.exports: $Exports<'popmotion/reactions/types'>;
}
declare module 'popmotion/reactions/value.js' {
  declare module.exports: $Exports<'popmotion/reactions/value'>;
}
declare module 'popmotion/transformers.js' {
  declare module.exports: $Exports<'popmotion/transformers'>;
}
