// flow-typed signature: 7934affa75f5e3188058a9d3c584648c
// flow-typed version: <<STUB>>/style-value-types_v^1.0.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-value-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-value-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-value-types/dist/style-value-types.min' {
  declare module.exports: any;
}

declare module 'style-value-types/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-value-types/dist/style-value-types.min.js' {
  declare module.exports: $Exports<'style-value-types/dist/style-value-types.min'>;
}
declare module 'style-value-types/lib/index.js' {
  declare module.exports: $Exports<'style-value-types/lib/index'>;
}
